### PR TITLE
Linux: add revoking /etc/ca-certificates.conf.

### PR DESCRIPTION
**Pull request by weakish**

### CODE REVIEW

**Comment by phoeagon** [comment]
I don't think your script is revoking each CA as in Windows version. Take a look at: https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online .

I understand that `ca-certificates` may be lacking some Root CA certs on this. So I'm more concerned about whether lack of a Root CA is the same as explicitly distrusting them. Also by doing so you run into risks of future ca-certificates adding those too.

**Comment by weakish** [comment]
> I don't think your script is revoking each CA as in Windows version. 
> I understand that `ca-certificates` may be lacking some Root CA certs on this. 

Hmm, I think we don't need to revoke CA that Liunx are not trusted by default.

> I'm more concerned about whether lack of a Root CA is the same as explicitly distrusting them.

`update-certificates` basically do:

1. soft link certs under `/usr/share/ca-certificates` in `/etc/ssl/certs/`
2. generate `/etc/ssl/certs/ca-certificates.crt` which include all trusted certs

(We do not consider `/usr/local/share/ca-certificates` yet.)

A normal line in `/etc/ca-certificates.conf`

- will be included in 1 and 2
- If it begins with `!`, it will not be included in both 1 and 2.
- If a cert in `/usr/share/ca-certificates` does not have a corresponding line in `/etc/ca-certificates.conf`:

    * it will not be included in 2, *but* be included in 1
    * it will not be included in both 1 and 2 if we use `--fresh`.

> run into risks of future ca-certificates adding those

Since `ca-certificates.conf` has been modified, if a future version of `ca-certificates` ships a new version
of it, package manager will warn against the change, and the default option is keep the modified file.
So current users are unlikely be affected.
Future users may be affected, but this script may be updated at that time.

**Comment by phoeagon** [comment]
Well, looks OK-ish to me.
But I'm still a little concerned about the "local cert" part. Since `ca-certificates` manages certs solely as files, what if there are multiple files that are exactly the same? Is it possible if we make a blacklist of public key checksums and check each cert's PKI against it (especially the local cert part). I would rather lie my confident on public key checksums than assuming my distro doesn't have a weird `ca-certificates` package.

**Comment by weakish** [comment]
> Since `ca-certificates` manages certs solely as files

Except for the black hole: `/etc/ca-certificates/update.d`, which is a mechanism for other programs to update certs. Scripts under there will be run when `update-ca-certificates`, and those scripts may do arbitrary things (put certs in directories outside `/etc/ssl`, the certs may be in other format, etc.).

> still a little concerned about the "local cert" part.

Certs in `/usr/local/share/ca-certificates` cannot be blacklisted in `/etc/ca-certificates`, and even if we remove it from the directory, we cannot avoid future software update install it again. So manual audit is still required to figure out which program installed them.

Fortunately `/usr/local` is owned by user, distribution packages including `ca-certificates` won't touch it.

> I would rather lie my confident on public key checksums than assuming my distro doesn't have a weird ca-certificates package.

Added. Now after `update-ca-certificates`, it will check if blacklisted certificates' sha1 match trusted certificates'.

**Comment by phoeagon** [comment]
Please *rebase* these changes so that it automatically merges. (Once `sha1` is resolved I'd merge it. thX! :-)

**Comment by weakish** [comment]
@phoeagon rebased

**Pull request merged**
