### PR TITLE
Reorganize shared certifications

### PR DESCRIPTION
**Pull request by ntkme**
This PR reorganizes online certifications.

The intention of it is to **remove hardcoded** filenames or SHA1 fingerprints from scripts as much as possible.

Changes:

1. Move online certificates to `Shared/Certificates`.
    - Details: [Shared/Certificates/README.md](https://github.com/chengr28/RevokeChinaCerts/blob/reorganize-certs/Shared/Certificates/README.md)
2. Certificates are categorized in txt files as SHA1 fingerprint, so we can **avoid hardcoding** a lot. 
    - Window
        - Need to distinguish between Root CA, Intermediate CA and SSL.
        - Need certificates file, type and SHA1.
    - Linux
        - Need to distinguish between [Root CA and Intermediate CA] and [SSL].
        - Need certificates file, type and SHA1.
    - Mac
        - No special requirement.
        - Only need SHA1.
    - So we have following lists of SHA1 fingerprint:
        - Certificates/Severity.High.Intermediate.CA.txt
        - Certificates/Severity.High.Root.CA.txt
        - Certificates/Severity.High.SSL.txt
        - Certificates/Severity.Medium.Intermediate.CA.txt
        - Certificates/Severity.Medium.Root.CA.txt
        - Certificates/Severity.Medium.SSL.txt
        - Certificates/Severity.Low.Intermediate.CA.txt
        - Certificates/Severity.Low.Root.CA.txt
        - Certificates/Severity.Low.SSL.txt
3. Certificates are named as their SHA1 fingerprints as they are categorized using fingerprints.
    - So the any list above can be easily used as a list of filenames.
4. Hunman Readable Certificates Details are generated by `openssl`. So we can remove some redundant info in Wiki.
    - [Severity.High.md](https://github.com/chengr28/RevokeChinaCerts/blob/reorganize-certs/Shared/Certificates/Severity.High.md)
    - [Severity.Medium.md](https://github.com/chengr28/RevokeChinaCerts/blob/reorganize-certs/Shared/Certificates/Severity.Medium.md)
    - [Severity.Low.md](https://github.com/chengr28/RevokeChinaCerts/blob/reorganize-certs/Shared/Certificates/Severity.Low.md)

Examples of updated implementation reflecting the changes:
- [Linux/revoke-china-certs.sh](https://github.com/chengr28/RevokeChinaCerts/blob/reorganize-certs/Linux/revoke-china-certs.sh)
- [Mac/build-trust-settings.sh](https://github.com/chengr28/RevokeChinaCerts/blob/reorganize-certs/Mac/build-trust-settings.sh)

Todo:

- [x] Update and test Android version
- [x] Update and test Linux version
- [x] Update and test Mac version
- [x] Update and test Windows version @chengr28
- [x] Write update hooks
- [x] Remove online certs from Windows version

@chengr28 @phoeagon What do you guys think?

### CODE REVIEW

**Comment by phoeagon** [comment]
I don't think certs should be named after the SHA1 fingerprint, since it burdens manual overriding (say, re-installing a particular cert for trust). But so long as we isolate them we should have more flexibility on this once we want to change it.

I do think that having a centralized cert DB would ease up maintenance. I suspect that for legacy reasons  intermediate indices of certs be retained, but let's provide a script to automatically generate those intermediate files. Maybe even setup Travis CI to continuous test if someone forgot to run the update script before commit (only owner can do this I think @chengr28 )

**Comment by ntkme** [comment]
Agree with your point that it's kind of hard to find a particular cert, but it's just for a simpler structure, which makes parsing easier for all kind of shell (especially for windows which it's a pain).

Initially my idea was still using certificates' subject names, then make SHA1 named symlink to the real cert, but it doesn't work well on windows. Another choice would be have SHA1 <-> certs mapping text files, again not very friendly for windows.

So, this PR is really my compromise to make it easy for windows version to catch up.

And as a workaround for finding cert, those cert information ".md" files are generated for searching.

**Comment by phoeagon** [comment]
Although `pem` and `crt` are similar, why are you changing the certs from `crt` to `pem`? I don't see why we should risk at all.

**Comment by phoeagon** [comment]
@weakish Are these the only place you referenced path to any certificates? (changed in 092e5d36381584ce6144e7a80efe00afc3f1011e and 76adf4c3fd84a65366b1c52880ba670101c519ee)

**Comment by phoeagon** [comment]
@ntkme Added default value for missing `SEVERITY` & `TYPE`

**Comment by ntkme** [comment]
@phoeagon Reverted the `.pem` to `.crt`

**Comment by ntkme** [comment]
@phoeagon I think you can probably remove one of `certsum_*_sorted.txt` and `certsum_*.txt` series, they are exactly same now because the `certificates.sh` returns sorted result.

**Comment by ntkme** [comment]
Quoted variables involving path. When you miss them, any whitespace character in the `$PWD` can be evil.

**Comment by phoeagon** [comment]
@ntkme Does `certificates.sh` rely on sorted indices? -Also I don't feel like doing so because I don't know why @weakish checked-in in this way. -

**Comment by phoeagon** [comment]
@ntkme Please add `update.sh` to the last step of adding a new certificate.

**Comment by ntkme** [comment]
@phoeagon Done. Also rewrote your android script so it works for both Linux and Mac.

**Comment by phoeagon** [comment]
@ntkme Hi! I think I would want the Android `_blacklist.txt` files to be sorted. Not that Android mandates so, but that should make it easier to check if an actual difference occurs if the file is actually updated. Do you recommend `sort` or anything else that reduces dependencies?

**Comment by ntkme** [comment]
Yes, `... | sort | tr '\n' ','` should be good enough. BSD sort and GNU sort are interchangeable.

**Comment by weakish** [comment]
> Are these the only place you referenced path to any certificates?

@phoeagon Provided that certsum*.txt are already handled by `update.sh`, yes.

> I think you can probably remove one of `certsum_*_sorted.txt` and `certsum_*.txt series`

@ntkme @phoeagon I made `certsum_*.txt` according  to WiKi (so it is easier for human to review it against the WiKi), then sort them to  `certsum_*_sorted.txt` for comparing with sha1 fingerprints of certs on system. Now since redundant info is removed from Wiki, and documentation and `certsum_*_sorted.txt` are all generated by `update.sh` automatically, I think there is no need to keep both `certsum_*_sorted.txt` and `certsum_*.txt`.

**Comment by chengr28** [comment]
Windows version seems working perfectly. Converting hardcore filename to SHA-1 fingerprint filename is OK, after we list their mapping into text files, readme documents or wiki(It seems to have done).

**Comment by phoeagon** [comment]
I have added a tag `pre-reorganize-certs` just in case.

**Pull request merged**
